#!/usr/bin/env bash

JAVA=""
JAVA_OPTS="-jar"
JARNAME="jcolorize.jar"

if [ "x$JAVA_HOME" != "x" ]; then
	JAVA="$JAVA_HOME/bin/java"
else
	# TODO: Test if we java is installed and check version
	JAVA="java"
fi

exec $JAVA $JAVA_OPTS ${JARNAME} "$@"
